### ISSUE TITLE
Microcks without Auth

### ISSUE THREAD

**Issue by vmary2014** [microcks/microcks#484]
Hi there
This tool is really amazing, and I wondered if there a way to spin Microcks in our CI (we use CircleCI) without keycloak ?
We're running this on a closed system and the idea would be that we just start Microcks, and use the CLI to load the yaml schemas to create the mock api
For us Keycloak takes a long time to start, and we also have issues communicating with it in Circleci with the current docker-compose config
Thanks
Vincent

**Comment by lbroudoux** [comment]
Hi @vmary2014 and thanks for the nice words!
As of today, it is not possible to bypass Keycloak but I'd like to investigate this topic to be able to do that. Especially now that we have a solid docker-compose setup, it would be even easier for developers to not have the Keycloak part deployed. I'll probably take time to look at this but not before a month or two.

**Comment by vmary2014** [comment]
> Hi @vmary2014 and thanks for the nice words!
> As of today, it is not possible to bypass Keycloak but I'd like to investigate this topic to be able to do that. Especially now that we have a solid docker-compose setup, it would be even easier for developers to not have the Keycloak part deployed. I'll probably take time to look at this but not before a month or two.

Thanks for replying, looking forward to that possibility being implemented in future.

**Comment by lbroudoux** [comment]
This issue will be integrated in larger #515 epic

**Comment by lbroudoux** [comment]
Hi @vmary2014 ! If still interested in this one, we've committed some stuffs to test yesterday. Documentation is not yet ready but I'll be able to send you some informations for a test drive. Let me know.

**Comment by vmary2014** [comment]
> Hi @vmary2014 ! If still interested in this one, we've committed some stuffs to test yesterday. Documentation is not yet ready but I'll be able to send you some informations for a test drive. Let me know.

Hi @lbroudoux I'll be happy to give it a try at some point. Thanks.

**Comment by markus-arndt-senacor** [comment]
@lbroudoux That looks great and I'd like to use 'keycloak.enabled: false' on k8s / helm (https://github.com/microcks/microcks/blob/master/install/kubernetes/README.md), but I couldn't do it. Will that be made possible?

**Comment by lbroudoux** [comment]
That's look legit! Please create a new issue so that we won't forget to a address this use-case as well (and we all also have a owner to help validate stuff once ready 😉).

**Comment by snarasin1** [comment]
> @lbroudoux That looks great and I'd like to use 'keycloak.enabled: false' on k8s / helm (https://github.com/microcks/microcks/blob/master/install/kubernetes/README.md), but I couldn't do it. Will that be made possible?



> @lbroudoux That looks great and I'd like to use 'keycloak.enabled: false' on k8s / helm (https://github.com/microcks/microcks/blob/master/install/kubernetes/README.md), but I couldn't do it. Will that be made possible?

@lbroudoux  is the above done? I still cant do 'keycloak.enabled: false' on k8s / helm
